name: bb.flutter
description: bbasic
version: 0.0.4

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: any
  intl: any
  path_provider: any
  crypto: any
  image: ^4.5.4
  jpeg_encode: any


  url_launcher: any
  shared_preferences: any
  diacritic: any
  flutter_color: any
  flutter_svg: any
  ansi_colorizer: any
  stack_trace: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
 uses-material-design: true
