name: bb.flutter
description: bbasic
version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bb_dart:
    git: https://github.com/aestesis/bb.dart.git
  collection: any
  intl: any
  path_provider: any
  crypto: any
  image: any


  url_launcher: any
  shared_preferences: any
  diacritic: any
  flutter_color: any
  flutter_svg: any
  ansi_colorizer: any
  stack_trace: any
  native_device_orientation: any


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
 uses-material-design: true
